friend1 = int(input("Enter friend 1's name:"))
friend1bd = int(input("Enter friend 1's birthdate:"))
friend2 = int(input("Enter friend 2's name:"))
friend2bd = int(input("Enter friend 2's birthdate:"))
friend3 = int(input("Enter friend 3's name:"))
friend3bd = int(input("Enter friend 3's birthdate:"))
friend4 = int(input("Enter friend 4's name:"))
friend4bd = int(input("Enter friend 4's birthdate:"))
friend5 = int(input("Enter friend 5's name:"))
friend5bd = int(input("Enter friend 5's birthdate:"))

print("Here are Raj's friends' names and birthdays:")
print(friend1, friend1bd)
print(friend2, friend2bd)
print(friend3, friend3bd)
print(friend4, friend4bd)
print(friend5, friend5bd)
